image:
  - Visual Studio 2019
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build &&
    cd build &&
    cmake c:\projects\source -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 16 2019" &&
    cmake --build . -- -m
