name: github-linux

on: [push, pull_request]

jobs:
  linux-release-serial:
    # simple serial release build using g++

    name: linux release serial
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        ./contrib/utilities/download_clang_format
    - name: info
      run: |
        g++ -v
        cmake --version
    - name: configure
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -D DEAL_II_CXX_FLAGS='-Werror' .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-serial-detailed.log
        path: detailed.log
    - name: build
      run: |
        make -j 2
        
  linux-debug-parallel-simplex:
    # simple parallel debug build using g++ with simplex configuration enabled

    name: linux debug parallel simplex
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: modules
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ginggs/deal.ii-9.2.0-backports
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends \
            numdiff \
            libp4est-dev \
            trilinos-all-dev \
            petsc-dev \
            libmetis-dev
    - name: info
      run: |
        mpicc -v
        cmake --version
    - name: configure
      run: |
        cmake -D CMAKE_BUILD_TYPE=Debug \
              -D DEAL_II_CXX_FLAGS='-Werror' \
              -D DEAL_II_WITH_MPI="ON" \
              -D DEAL_II_WITH_SIMPLEX_SUPPORT="ON" \
              -D DEAL_II_WITH_TRILINOS="ON" \
              -D DEAL_II_WITH_PETSC="ON" \
              -D DEAL_II_WITH_METIS="ON" \
              -D DEAL_II_COMPONENT_EXAMPLES="OFF" \
              .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-simplex-detailed.log
        path: detailed.log
    - name: build
      run: |
        make -j 2
    - name: test
      run: |
        make -j 2 setup_tests_simplex
        ctest --output-on-failure -j 2 
