name: github-CI

on: [push, pull_request]

jobs:
  osx-serial:
    # simple serial build using apple clang

    name: OSX serial build
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: info
      run: |
        g++ -v
        cmake --version
    - name: configure
      run: |
        cmake -D CMAKE_BUILD_TYPE=Debug -D DEAL_II_CXX_FLAGS='-Werror' .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: detailed.log
        path: detailed.log
    - name: build
      run: |
        make -j 2
        make -j 2 test # quicktests

  osx-parallel:
    # MPI build using apple clang

    name: OSX parallel build
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        brew install openmpi
        cmake --version
        # uncomment these for a gcc based build
        #export OMPI_CXX=g++-9
        #export OMPI_CC=gcc-9
        #export OMPI_FC=gfortran-9
    - name: info
      run: |
        g++-9 -v
        mpicxx -v
        cmake --version
    - name: configure
      run: |
        CC=mpicc CXX=mpic++ cmake -D CMAKE_BUILD_TYPE=Debug -D DEAL_II_CXX_FLAGS='-Werror' -D DEAL_II_WITH_MPI=on .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: detailed.log
        path: detailed.log
    - name: build
      run: |
        make -j 2
        make -j 2 test #quicktests
